### ISSUE TITLE
On mobile, you can't press "q"

### ISSUE THREAD

**Issue by quittle** [bschlenk/set#2]
That feature is unusable on mobile

**Comment by bschlenk** [comment]
I added a button that lets you add more cards if you don't think there is a set. I'll make a new issue to update the design readme to reflect this change.

**Comment by bschlenk** [comment]
https://github.com/bschlenk/set/issues/2

**Comment by bschlenk** [comment]
Added https://github.com/bschlenk/set/issues/5 as a follow up
